### ISSUE TITLE
You do not have access to the Apex class named 'SiteLoginController'.

### ISSUE THREAD

**Issue by Zeakk** [SalesforceLabs/Configurable-Self-Registration-for-Experience-Cloud#39]
I installed the plugin to our environment and added the Custom Login component to the experience page. I added the Custom Login - Guest Access to the partner user's permission set and upon trying to login using the new component I receive the error message below. I even added the apex class to the profile used for partner users and still no dice.

You do not have access to the Apex class named 'SiteLoginController'

Any ideas or suggestions to help with this error message? Thank you! I appreciate this plugin as the out of the box login form doesn't have the ability to allow folks to see their password as they enter it.

I should've stated on v1.8.

**Comment by jloweSFDC** [comment]
Hi @Zeakk - this should be simple to resolve. An experience cloud site when unauthenticated access the login page and component as the guest user for that site. Therefore, you need to assign that permission set to the guest user. Currently, it sounds like you've assigned it to a partner user i.e. an authenticated user which won't have any effect on the login component and causes the error. I'll mark this as closed as I'm fairly confident that is what it is, but do let me know if this isn't the case.

**Comment by Zeakk** [comment]
Thank you! I totally misread the admin guide...now all is working. Appreciate the component and your time.
