### ISSUE TITLE
"No apex action available for expcloud.SiteRegistrationController.getCustomConfiguration"

### ISSUE THREAD

**Issue by Mike-Cleaver-LB** [SalesforceLabs/Configurable-Self-Registration-for-Experience-Cloud#46]
I have just installed the latest version into our dev sandbox (1.86) and it sounds like the siteregcontroller is missing a method?
![image](https://github.com/user-attachments/assets/816ac8dd-54c6-46c0-8e6c-80c43c125fa2)

**Comment by jlowe-SFDC** [comment]
Hi @Mike-Cleaver-LB - Have you upgraded in that sandbox or a fresh install? The new release requires you to remove the existing component if you are upgrading and replace it with a new one.  See the release notes: https://salesforce.quip.com/Af8CAQSB5eEA

The getCustomConfiguration method has moved to the SiteUtilities class as it is shared with the login component. There is no reference to SiteRegistration for this method in the new LWC:

![image](https://github.com/user-attachments/assets/d50d326e-0bbc-45e1-b3d4-445adb3bb695)

**Comment by Mike-Cleaver-LB** [comment]
RTFM sorry!
